language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script: 
 - echo 'date.timezone = "UTC"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - curl -sS https://getcomposer.org/installer | php
 - php composer.phar install --no-interaction
 - vendor/bin/phpunit --version
 - mkdir -p build/logs

script: 
 # - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
 - vendor/bin/phpspec run --format=pretty

after_script:
 - php vendor/bin/coveralls -v
